### ISSUE TITLE
A new work

### ISSUE THREAD

**Issue by omrysendik** [lzhbrian/image-to-image-papers#10]
Hi,

this repository has really helped me quite a lot in my research!!!
I uploaded our new work for unsupervised image to image translation, specifically for manifesting latent space constraints. see below for more info:
https://arxiv.org/abs/1901.04530

I would be grateful if you can add our work to the list of unsupervised image to image translation.

Thank you

**Comment by lzhbrian** [comment]
Added, Thanks!
