### ISSUE TITLE
What differences are there between image translation and style transfer？

### ISSUE THREAD

**Issue by Feiyu-Zhang** [lzhbrian/image-to-image-papers#12]
I think style transfer is a sub-class of image translation. How about you？

**Comment by lzhbrian** [comment]
I agree with you. Style transfer is a type of image translation.

**Comment by omrysendik** [comment]
I disagree, since strictly speaking, it's not a sub class. 
Image to image translation can achieve style transfer, but they can do more than just that. 
Perhaps most importantly, they can achieve domain translation, such as RGB to IR, edges to images, and many more uses.

**Comment by lzhbrian** [comment]
Yes, image-to-image translation can achieve many tasks, and image style transfer is one of them.
I do not see the conflict among us.
