### ISSUE TITLE
PI-REC: Progressive Image Reconstruction Network With Edge and Color Domain

### ISSUE THREAD

**Issue by youyuge34** [lzhbrian/image-to-image-papers#4]
arxiv:  https://arxiv.org/abs/1903.10146
github:  https://github.com/youyuge34/PI-REC
       
Can you add it? Thanks a lot!      
Or maybe I could pull a request.

**Comment by lzhbrian** [comment]
Interesting work, pls make a PR, if you would like.
It's a supervised method right? From edge and color to image.

**Comment by youyuge34** [comment]
@lzhbrian Right，PI-REC is supervised when training, but the paired data is auto-extracted from GT without any manual annotation.       
I have made a PR, THX again!
