### ISSUE TITLE
some new works

### ISSUE THREAD

**Issue by imlixinyang** [lzhbrian/image-to-image-papers#6]
1. DRIT++: Diverse Image-to-Image Translation via Disentangled Representations
https://arxiv.org/pdf/1905.01270.pdf
extend drit to mult-domain task.
2. FUNIT: Few-Shot Unsupervised Image-to-Image Translation
https://arxiv.org/pdf/1905.01723.pdf
find general coding for class by few images.
3. Attribute Guided Unpaired Image-to-Image Translation with Semi-supervised Learning
https://arxiv.org/pdf/1904.12428.pdf
jointly solve multi-modal and multi-label tasks, introduce a semi-supervised training process(previous 'unsupervised' is actually unpaired), and some new tasks are proposed.

**Comment by lzhbrian** [comment]
Added, Thanks!

**Comment by szq0214** [comment]
Hi @lzhbrian, there is another work on unsupervised instance-level image-to-image translation with a very large new dataset **INIT**.  This paper has been accepted in CVPR 2019.
Towards Instance-level Image-to-Image Translation
https://arxiv.org/abs/1905.01744
Project page: http://zhiqiangshen.com/projects/INIT/index.html.

**Comment by lzhbrian** [comment]
Thanks! Interesting work @szq0214 
Do you plan on releasing the code?

**Comment by imlixinyang** [comment]
I'm an author of the third paper(Attribute Guided Unpaired Image-to-Image Translation with Semi-supervised Learning) of this issue and wonder if there is a chance for your advice or opinions of this paper because of a little lack of self-confidence with my first paper which is written not so well. 
@lzhbrian @szq0214

**Comment by szq0214** [comment]
Hi @lzhbrian, Thank you very much! 
I'm too busy in the lab recently and I'm not sure when I have time to clean it. ==
