### ISSUE TITLE
New works

### ISSUE THREAD

**Issue by imlixinyang** [lzhbrian/image-to-image-papers#7]
1. Image-to-Image Translation with Multi-Path Consistency Regularization
https://arxiv.org/pdf/1905.12498.pdf
2. Mask-Guided Portrait Editing with Conditional GANs
https://arxiv.org/pdf/1905.10346.pdf
3. Toward Learning a Unified Many-to-Many Mapping for Diverse Image Translation
https://arxiv.org/pdf/1905.08766.pdf

And AGUIT's project: https://github.com/imlixinyang/AGUIT

**Comment by lzhbrian** [comment]
Thanks, I will add it to the list.
I am quite busy these days. Sorry for the delay.

**Comment by lzhbrian** [comment]
added, thanks!
