### ISSUE TITLE
New work

### ISSUE THREAD

**Issue by orenkatzir** [lzhbrian/image-to-image-papers#8]
Hi, 
this repository has helped it a lot during my research, thank you for opening and maintaining it.

We have uploaded our new work for unsupervised image to image translation, specifically for cross-domain translation (i.e. animals), by utilizing the semantics encoded in pre-trained network, e.g. VGG. Our translation is performed in a cascaded, deep-to-shallow, fashion, along the deep feature hierarchy, see [here](https://arxiv.org/abs/1906.01526) for more info.

I would be grateful if you can add our work to the list of unsupervised image to image translation.

Thank you

**Comment by lzhbrian** [comment]
Thanks, nice work!
added in ac2b8467
