### ISSUE TITLE
some new works

### ISSUE THREAD

**Issue by Ha0Tang** [lzhbrian/image-to-image-papers#9]
1. Multi-Channel Attention Selection GAN with Cascaded Semantic Guidance for Cross-View Image Translation (CVPR 2019); code: https://github.com/Ha0Tang/SelectionGAN
2. GestureGAN for Hand Gesture-to-Gesture Translation in the Wild (ACM MM 2018); code: https://github.com/Ha0Tang/GestureGAN
3. Attention-Guided Generative Adversarial Networks for Unsupervised Image-to-Image Translation (IJCNN 2019 oral); code: https://github.com/Ha0Tang/AttentionGAN

**Comment by lzhbrian** [comment]
Added, Thanks!
